CGO_ENABLED=0 for all build steps of Dockerfile
When running a docker buildx build for ARM64:
docker buildx build --no-cache --platform linux/arm64/v8 -f Dockerfile -t "any-tag-here" .

The build fails:
 => ERROR [build-env 8/8] RUN set -e ;    go test ./test/*.go;    go test ./pkg/*;    cd cmd/costmodel;    CGO_ENABLED=0 GOOS=linux GOARCH=amd64     go build -a -installsuffix cgo -o /go/bin/app                                                      26.5s
------
 > [build-env 8/8] RUN set -e ;    go test ./test/*.go;    go test ./pkg/*;    cd cmd/costmodel;    CGO_ENABLED=0 GOOS=linux GOARCH=amd64     go build -a -installsuffix cgo -o /go/bin/app:
------
Dockerfile:13
--------------------
  12 |     # Build the binary
  13 | >>> RUN set -e ;\
  14 | >>>     go test ./test/*.go;\
  15 | >>>     go test ./pkg/*;\
  16 | >>>     cd cmd/costmodel;\
  17 | >>>     CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
  18 | >>>     go build -a -installsuffix cgo -o /go/bin/app
  19 |
--------------------
error: failed to solve: process "/dev/.buildkit_qemu_emulator /bin/sh -c set -e ;    go test ./test/*.go;    go test ./pkg/*;    cd cmd/costmodel;    CGO_ENABLED=0 GOOS=linux GOARCH=amd64     go build -a -installsuffix cgo -o /go/bin/app" did not complete successfully: exit code: 1

Based on this part of the error message:
go build runtime/cgo: gcc: exit status 1

I suspected the missing GCC. After making this commit's changes, the
buildx command succeeds.